version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: gshjis
      POSTGRES_DB: pomodoro
    shm_size: 128mb

  service:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "make run"

volumes:
  postgres_data:
