version: "3.8"

services:
  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password # Пароль для суперпользователя
      POSTGRES_USER: postgres # Имя пользователя (опционально, по умолчанию 'postgres')
      POSTGRES_DB: pomodoro # Создаваемая БД при старте
    volumes:
      - postgres_data:/var/lib/postgresql/data # Сохраняем данные между перезапусками

volumes:
  postgres_data:
