"""Fixing

Revision ID: 32bfc3f339a5
Revises: ccc0060a7087
Create Date: 2025-07-14 15:13:38.698297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bfc3f339a5'
down_revision: Union[str, Sequence[str], None] = 'ccc0060a7087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('owner_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'owner_id')
    # ### end Alembic commands ###
