"""fixed enums

Revision ID: 526165949c5e
Revises: 8ca3a9b1311b
Create Date: 2025-07-14 15:59:09.190597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '526165949c5e'
down_revision: Union[str, Sequence[str], None] = '8ca3a9b1311b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'permissions',
               existing_type=postgresql.ENUM('READ', 'WRITE', 'DELETE', name='permission'),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'permissions',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('READ', 'WRITE', 'DELETE', name='permission'),
               existing_nullable=True)
    # ### end Alembic commands ###
