"""add_is_deleted_to_tasks

Revision ID: e8cb82f44163
Revises: 9655bcdbffe2
Create Date: 2025-07-09 09:09:43.141804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cb82f44163'
down_revision: Union[str, Sequence[str], None] = '9655bcdbffe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_deleted')
    # ### end Alembic commands ###
